apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-health-check-tzne
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-health-check-tzne
    app.kubernetes.io/part-of: e2e-nodejs
  name: nodejs-health-check-tzne
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-health-check-tzne
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-health-check-tzne
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pdkl-tenant/e2e-nodejs/nodejs-health-check-tzne@sha256:c16dd107778727514e9d1248b3ca402b9f515c3d003a1942d5678c887a927d16
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
