apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-health-check-cp0a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-health-check-cp0a
    app.kubernetes.io/part-of: e2e-nodejs
  name: nodejs-health-check-cp0a
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-health-check-cp0a
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-health-check-cp0a
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pdkl-tenant/e2e-nodejs/nodejs-health-check-cp0a@sha256:df73345214f5eb8a238dcb0918c2cb6ad178d5ec3cbdde6b233c73424d9d4b3b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
